language: go

go:
    - 1.8
    - 1.9
    - "1.10"

script:
    - pushd vendor/github.com/satori/go.uuid/ && go test -bench=. && popd
    - pushd vendor/github.com/rcrowley/go-metrics/ && go test -bench=. && popd

